[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
libs = ["lib"]
src = "src"
test = "test"
out = "out"
evm_version = "cancun"
ffi = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
