[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = true

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[rpc_endpoints]
hyperliquid = "${RPC_URL}"
local = "http://localhost:8545"

[etherscan]
hyperliquid = { key = "${ETHERSCAN_API_KEY}" }
